### ISSUE TITLE
📢 Azure/login v2 Release Announcement 

### ISSUE THREAD

**Issue by MoChilia** [MoChilia/ActionDemo#2]
👀 **What’s new in `azure/login@v2`?**

- The default runtime of `azure/login` is updated from `Node16` to `Node20` due to [the upcoming deprecation of Node16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).

⚠️ **This is breaking change**

- If you're using `azure/login` with a self-hosted runner, ensure it's running [Actions Runner image v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) or later.

To apply this change, please update the version of `azure/login` to `v2` in your workflow files.
```yaml
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
```
